### ISSUE TITLE
Validation error when creating an Rftemplate with a name that contains a space

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#11]
When attempting to create a `Rftemplate` resource I get a validation error if the name contains a space. I believe this to be an error as you can create an Rftemplate in the portal with a space in the name without issue, but using the TF provider, it triggers a validation error.

**Comment by tmunzer** [comment]
Hi @zbuchheit , can you test v0.1.24?

**Comment by zbuchheit** [comment]
This looks to be fixed. Thank you!
