### ISSUE TITLE
site datasource returning empty array

### ISSUE THREAD

**Issue by tmunzer** [Juniper/terraform-provider-mist#16]
in v0.1.25 I am running into an issue where the data lookup for sites is returning an empty array. Perhaps I am doing something wrong or not following a breaking change?

```
data "mist_sites" "sites" {
  org_id = "redacted"
}

resource "mist_site_wlan" "wlan_one" {
  ssid              = "wlan_one"
  site_id           = data.mist_sites.sites.sites[0].id
  limit_bcast = true
  allow_ssdp = true
}

```

_Originally posted by @zbuchheit in https://github.com/Juniper/terraform-provider-mist/issues/14#issuecomment-2329426406_

**Comment by tmunzer** [comment]
> ```hcl
> data "mist_sites" "sites" {
>   org_id = "redacted"
> }
> output "mist_sites_data" {
>   value = data.mist_sites.sites
> }
> ```
> 
> results in
> 
> ```
> Changes to Outputs:
>   + mist_sites_data = {
>       + org_id = "redacted"
>       + sites  = []
>     }
> ```

I tested on my side and I don't have any issue, the provider is getting the list of sites as expected. 
Just to be sure, can you validate you still have sites in this organization?

**Comment by zbuchheit** [comment]
on version 0.1.24 it gives me the Primary site, but on version 0.1.25 the sites come back as empty with the same HCL code

**Comment by zbuchheit** [comment]
here is what comes back on version 0.1.24
```
  + mist_sites_data = {
      + org_id = "redacted"
      + sites  = [
          + {
              + address            = null
              + alarmtemplate_id   = null
              + aptemplate_id      = null
              + country_code       = "US"
              + created_time       = 1723235137
              + gatewaytemplate_id = null
              + id                 = "redacted"
              + latlng             = {
                  + lat = redacted
                  + lng = -redacted
                }
              + modified_time      = 1723235137
              + name               = "Primary Site"
              + networktemplate_id = null
              + notes              = null
              + org_id             = "redacted"
              + rftemplate_id      = null
              + secpolicy_id       = null
              + sitegroup_ids      = null
              + sitetemplate_id    = null
              + timezone           = "America/Los_Angeles"
            },
        ]
    }
```

**Comment by tmunzer** [comment]
weird, the only difference between 0.1.24 and 0.1.25 are in the webhook files, there is no changes on the Sites Datasource...

**Comment by tmunzer** [comment]
ok, I found the issue. I'll double check the other datasources and I'll publish the new version in the hour.

**Comment by tmunzer** [comment]
Hi @zbuchheit , can you check with v0.1.26?

**Comment by zbuchheit** [comment]
looks like it's good in v0.1.26. Thank you!
