### ISSUE TITLE
Incorrect default value for Wlan Roam Mode

### ISSUE THREAD

**Issue by JoshiiSinfield** [Juniper/terraform-provider-mist#19]
Hi,

I believe the case of 'none' is incorrect for the value of 'Default' Fast Roaming on a WLan.

When the default of 'none' is used the 'Default' option isn't selected on Mist portal.

Once updated on Mist portal and `terraform plan` performed the diff shows a difference in case.
```shell

      ~ roam_mode                              = "NONE" -> "none"

      ~ schedule                               = {
          ~ hours   = {
```

Please note - it's not a perpetual plan diff, it only shows up when correctly selecting 'Default' in the Mist portal.

I think the change is required here?:
https://github.com/tmunzer/mistapi-go/blob/main/mistapi/models/enums.go#L4328

Cheers,
Josh

**Comment by tmunzer** [comment]
Thanks @JoshiiSinfield , I'll update the SDK and the provider.

**Comment by JoshiiSinfield** [comment]
Hi @tmunzer 

That's done the trick. Appreciate the fast fixes!

**Comment by JoshiiSinfield** [comment]
Hi,

Yes apologies. Helps If I click the button to post the comment!

The validation of values work now, but the default value is still incorrect. 
The diff shows the below, when commenting out the parameter:

before
```hcl
 roam_mode = "NONE"
```

after
```hcl
#roam_mode = "NONE"
```

diff
```shell
  ~ roam_mode                              = "NONE" -> "none"
```

**Comment by tmunzer** [comment]
good catch, thanks, the default value was not updated.

**Comment by tmunzer** [comment]
Hi @JoshiiSinfield , can you test with v0.1.29?

**Comment by JoshiiSinfield** [comment]
tested with v0.1.31 and looks good now 👍 
Thanks for quick turnaround 👍
