### ISSUE TITLE
Add ability to configure site wlan portal_template_url, thumbnail, and portal_image

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#21]
Currently `portal_template_url` `thumbnail` `portal_image` are all read-only as part of site wlan. https://registry.terraform.io/providers/Juniper/mist/latest/docs/resources/site_wlan#read-only

I would like to be able to configure these.

**Comment by tmunzer** [comment]
These fields are Read Only on the API side:
* portal_image: generated when a portal image is uploaded to indicate where the image can be retrieved
* thumbnail: generated when a portal image has been customized. Indicates the thumbnail can be retrieved
* portal_template_url: generated when a portal is configured. Indicates where the portal template can be retrieved


I'll add two new resources:
* to upload the portal template (API Call https://www.juniper.net/documentation/us/en/software/mist/api/http/api/sites/wlans/update-site-wlan-portal-template) 
* to upload the portal image (API Call https://www.juniper.net/documentation/us/en/software/mist/api/http/api/sites/wlans/upload-site-wlan-portal-image)

**Comment by tmunzer** [comment]
Hi @zbuchheit , can you test with v0.1.29?

**Comment by zbuchheit** [comment]
- [x] site_wlan_portal_template
`works as expected`
- [ ] org_wlan_portal_template
throws an error
```tf
resource "mist_org_wlan_portal_template" "wlan_one" {
  org_id  = "redacted"
  wlan_id = "redacted"
  portal_template = {
    sms_message_format    = "Code {{code}} expires in {{duration}} minutes."
    sms_validity_duration = "10"
    page_title            = "Welcome To My Demo Portal"
    locales = {
      "fr-FR" = {
        page_title = "Bienvenue sur mon portail de démo"
      }
    }
  }
}
```
errors with
```
mist_org_wlan_portal_template.wlan_one: Creating...
╷
│ Error: Error creating Wlan
│ 
│   with mist_org_wlan_portal_template.wlan_one,
│   on main.tf line 10, in resource "mist_org_wlan_portal_template" "wlan_one":
│   10: resource "mist_org_wlan_portal_template" "wlan_one" {
│ 
│ Could not create Wlan, unexpected error: ResponseHttp404 occured: Not found. The API
│ endpoint doesn’t exist or resource doesn’ t exist

**Comment by tmunzer** [comment]
Hi @zbuchheit ,

I'm not able to replicate the issue. Can you validate the `wlan_id` is comming from a `mist_org_wlan` and not a `mist_site_wlan`?

Thanks

**Comment by zbuchheit** [comment]
let me verify and get back to you

**Comment by zbuchheit** [comment]
ah I think it was my error. I was creating a mist_site_wlan

**Comment by tmunzer** [comment]
cool, thanks for the confirmation!
Not sure if there is a way to add some validation on that...

**Comment by zbuchheit** [comment]
hmm, I would assume likely not given they are valid guid's, it wouldn't know if they are valid until runtime.

**Comment by tmunzer** [comment]
Hi @zbuchheit , I just released a new version which is adding the org_wlan_portal_image and site_wlan_portal_image.
They can be used to upload the portal background image.

**Comment by zbuchheit** [comment]
I'll check it out. Thanks @tmunzer

**Comment by zbuchheit** [comment]
Hi @tmunzer I was able to test it and it appears the resource works for the background. Is there a way to do this for the Logo as well or is that currently a limitation?

![image](https://github.com/user-attachments/assets/dece8178-bd45-4640-bab4-321ea1a5272f)

**Comment by tmunzer** [comment]
Hi @zbuchheit, 

Yes, I saw that when working on the background image. This is not a documented API (but from what I saw it’s using a public API anyway, it’s just a lack of documentation on our side).
I have two possibilities here:
#1: use the same resource for the background image and the logo. For me this makes totally sense, but it’s not following the best practices (one API call per resource)
#2: create a new resource for the logo, which may be a bit cumbersome.

Let me know if you have any preference.

Thanks

**Comment by zbuchheit** [comment]
I think the original issue is solved. I am going to open a new one requesting the logo feature and close this one. Thanks @tmunzer
