### ISSUE TITLE
Mist UI Crashes when `input_port_ids_egress` and `input_port_ids_ingress` are not provided to `switch_matching.rules.port_mirroring` 

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#22]
On resource `site_networktemplate`, when you don't provide `input_port_ids_egress` and `input_port_ids_ingress` as part of `switch_matching.rules.port_mirroring`  it will cause the Mist UI to crash.

**Comment by zbuchheit** [comment]
should this be fixed in the latest release as well @tmunzer ?

**Comment by tmunzer** [comment]
Yes, it should. I'll double check tomorrow

**Comment by zbuchheit** [comment]
this appears to be fixed in my testing
