### ISSUE TITLE
"Warning: Device not in the Org Inventory" while using `mist_org_inventory`

### ISSUE THREAD

**Issue by zPools** [Juniper/terraform-provider-mist#23]
I want to use the resource `mist_org_inventory` to claim an AP and eventually assign it to a site.

However, I get following error message while trying it.

```bash
mist_org_inventory.org_inventory: Creating...

 Warning: Device not in the Org Inventory
 
   with mist_org_inventory.org_inventory,
   on main.tf line 78, in resource "mist_org_inventory" "org_inventory":
   78: resource "mist_org_inventory" "org_inventory" {
 
 Device with Claim Code <obfuscated> is not in the Org Inventory



 Error: Provider produced inconsistent result after apply
 
 When applying changes to mist_org_inventory.org_inventory, provider "provider[\"registry.terraform.io/juniper/mist\"]" produced an unexpected new value: .devices: element 0 has vanished.
 
 This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

This is my terraform code:
```terraform
resource "mist_org_inventory" "org_inventory" {
  org_id = mist_org.terra_test_org.id
  devices = [
    {
      claim_code = "<obfuscated>"
    },
  ]
}
```
Worth mentioning that the AP will show up on the inventory in Mist, but Terraform cant do stuff with it.

The AP is currently released (from our prod site) and I can claim it by hand on my test side.
However, the goal is that we can do this by code and not by hand.

**Comment by tmunzer** [comment]
Hi @zPools ,

This may be because the claiming process failed at some point (AP already claimed somewhere, wrong claim code, ...).
I'll improve this resource to have a better error processing

**Comment by tmunzer** [comment]
Also, if the AP is already claimed and you don't want to manage the claiming process with Terraform, you can use the following HCL:
```hcl
resource "mist_org_inventory" "org_inventory" {
  org_id = mist_org.terra_test_org.id
  devices = [
    {
      mac = "<obfuscated>"
    },
  ]
}
```

**Comment by tmunzer** [comment]
required improvements when using `claim_code`:
- if the device is already claimed in the same Org, trigger a warning and add the device in the org inventory
- if the device is already claimed somewhere else, trigger an error
- if the claim code is invalid, trigger an error

**Comment by zPools** [comment]
Hey @tmunzer 
thank you for your answer. 

The claim code that I use is in state `released`. So it is not already use. 

Once I want to claim, the error appears. After that, the AP somehow appears in the Mist Inventory but Terraform cant access it

**Comment by tmunzer** [comment]
ok, got it. I'll check that.

Thanks

**Comment by zPools** [comment]
Shall I open a ticket within the Mist Dashboard? So you are able to access more confidential data?

**Comment by tmunzer** [comment]
No that's ok, I'll try to replicate it. Thanks a lot!

**Comment by zPools** [comment]
Hey @tmunzer,

just a quick additional information; Working with mac addresses doesn’t work either. Please see my attached screenshot.

<img width="1494" alt="Screenshot " src="https://github.com/user-attachments/assets/00f4c4d6-d3c4-4e5e-b038-9da3478e6631">

**Comment by tmunzer** [comment]
Thanks @zPools , I'll work on this today

**Comment by zPools** [comment]
Hi @tmunzer,
Unfortunately it does not work. Neither with v0.1.29 or v0.1.31.


```bash
mist_org_inventory.org_inventory: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to mist_org_inventory.org_inventory, provider "provider[\"registry.terraform.io/juniper/mist\"]" produced an unexpected new value:
│ .devices: element 0 has vanished.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

The warning now works as expected.

**Comment by tmunzer** [comment]
Hi @zPools ,

Can you [enable TF debug](https://developer.hashicorp.com/terraform/internals/debugging) and send me the logs by email?

Thanks

**Comment by tmunzer** [comment]
Hi @zPools , this version should fix the inventory issue(s).

Let me know if it's not the case.

**Comment by zPools** [comment]
Hi @tmunzer,

the `claim_code` now works as expected. Thank you!

Unfortunately the part with mac addresses seems to have a small bug.



If the an AP is unassigned, the code below works as expected:
```terraform
resource "mist_org_inventory" "org_inventory" {
  org_id = mist_org.terra_test_org.id
  devices = [
    {
      mac       = "123456aabbcc"
      site_id   = mist_site.site_munich.id
    }
  ]
}
```

But if I going to change the site of the AP to another site like this:

```terraform
resource "mist_org_inventory" "org_inventory" {
  org_id = mist_org.terra_test_org.id
  devices = [
    {
      mac       = "123456aabbcc"
      site_id   = mist_site.site_san_francisco.id
    }
  ]
}
```

Terraform will error out with following error code:
```bash
╷
│ Error: Error Assigning Devices to the Org Inventory
│ 
│   with mist_org_inventory.org_inventory,
│   on 6_inventory.tf line 11, in resource "mist_org_inventory" "org_inventory":
│   11: resource "mist_org_inventory" "org_inventory" {
│ 
│ Unable to assign the devices, unexpected error: ResponseHttp400 occured: Bad Syntax
╵
╷
│ Error: Device not found
│ 
│   with mist_org_inventory.org_inventory,
│   on 6_inventory.tf line 11, in resource "mist_org_inventory" "org_inventory":
│   11: resource "mist_org_inventory" "org_inventory" {
│ 
│ Unable to find device with MAC "123456aabbcc" in the Org Inventory
╵
```

I´ll send you the log file by mail

**Comment by tmunzer** [comment]
Thanks @zPools , the fix is ready, I'll publish a new version today or tomorrow.

**Comment by tmunzer** [comment]
Hi @zPools, FYI, v0.1.33 is published and should fix the inventory issues.

**Comment by zPools** [comment]
Thank you! Everything works as expected now!

If you work with mac addresses only and you are deleting the hcl resource, the device gets `unclaimed`. That should be written in the docs.

**Comment by tmunzer** [comment]
Yes, sorry, I should have mentioned it.
For "cloud ready" devices (with claim code) that have been added to TF with the MAC address, I was not able to find a way to identify them once they were removed from the configuration. 
My plan is still to only unclaim devices that have been added with the Claim Code.

I'll update the documentation for now. Thanks
