### ISSUE TITLE
Add ability to upload logo for wlan portal

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#26]
Currently we have the resource for the backround image which is both `mist_org_wlan_portal_image` and `mist_site_wlan_portal_image` it would be nice to have the ability to upload the logo for the wlan portal.

It appears the way this works today via the API is the image is base64 encoded and uploaded via a portal_template call as `logo`, `logoHeight`, and `logoWidth`

### Additional Context

Continuation of https://github.com/Juniper/terraform-provider-mist/issues/21#issuecomment-2344654012

**Comment by tmunzer** [comment]
Thanks you @zbuchheit . I'll add it in the next release

**Comment by tmunzer** [comment]
available in v0.1.34

**Comment by zbuchheit** [comment]
looks to be working, Thanks!
