### ISSUE TITLE
Authentication error when attempting to use org token

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#3]
When attempting to use the provider for the first time I am encountering an authentication error. I am attempting to authenticate via `MIST_API_TOKEN` using an org token. I have verified the API token is valid.

## Error Message 
```
│ Error: Authentication Error
│ 
│   with provider["registry.terraform.io/juniper/mist"],
│   on <empty> line 0:
│   (source code not available)
│ 
│ required field `email` is missing for type `Admin`
│ required field `first_name` is missing for type `Admin`
│ required field `last_name` is missing for type `Admin`
```

## Repro
```tf
terraform {
  required_providers {
    mist = {
      source = "juniper/mist"
      version = "0.1.16"
    }
  }
}

data "mist_sites" "sites" {
  org_id  =  "redacted"
}
```

## Additional Context
It appears this error message is coming from validation in the [mistapi-go admin struct](https://github.com/tmunzer/mistapi-go/blob/3ef09e46e7c0416c876983be74a3295e39ead771/mistapi/models/admin.go#L154C35-L169C2)

**Comment by zbuchheit** [comment]
I believe specifically the issue is coming from

https://github.com/Juniper/terraform-provider-mist/blob/e989330f1955272a52c74ccdff635e72390854c5/internal/provider/provider.go#L353 where SelfAccount won't respond with first_name last_name or email.

It will only respond with an object like
```
{
    "name": "pulumi-test-token",
    "privileges": [
        {
            "scope": "org",
            "org_id": "redacted",
            "role": "admin",
            "name": "Test Org"
        }
    ]
}
```

so that will cause the model validation to fail as referenced above

**Comment by tmunzer** [comment]
Hi @zbuchheit ,

I updated the mistapi-go SDK to fix the issue, and updated the terraform provider to use the latest version of the SDK. This issue should be fixed.

Thanks.

**Comment by zbuchheit** [comment]
Fixed via newest release of the SDK
