### ISSUE TITLE
Implement import functions for resources

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#4]
Currently it doesn't appear there is a way to implement resources with the provider since there is no `ImportState` functions for the resources. It would be nice to be able to import existing resources with the provider.

**Comment by tmunzer** [comment]
Hi Zachary,

This is planned. I'll start to work on it next week.

**Comment by tmunzer** [comment]
import

**Comment by tmunzer** [comment]
import functions have been added into v0.1.21
