### ISSUE TITLE
Mist UI issue with site_wxrule resource 

### ISSUE THREAD

**Issue by tmunzer** [Juniper/terraform-provider-mist#46]
Some fields required by the Mist UI are not populated when the wxrule is created by the provider.

**Comment by tmunzer** [comment]
I was not able to replicate the issue with the `mist_site_wxrule` resource, but only with the `mist_org_wxrule` resource which was not implementing the fixes from #24 .
The fixes have been added and validated.

**Comment by zbuchheit** [comment]
this issue has been confirmed as resolved as of the latest release
