### ISSUE TITLE
Objet : Problème avec la récupération des AP dans le provider Mist

### ISSUE THREAD

**Issue by Khadimbkd** [Juniper/terraform-provider-mist#49]
Bonjour,
Je rencontre actuellement un problème en utilisant le provider Mist pour Terraform, en particulier pour récupérer et gérer les informations des points d’accès (AP).
Voici les détails du problème :
• Contexte : Je souhaite lister et configurer plusieurs AP via Terraform en utilisant le provider Mist.
• Problème : Je tente d’accéder aux AP à partir des données **mist_org_inventory.** Cependant, les chemins utilisés (comme **inventory.devices** ou **inventory.ap**) génèrent des erreurs telles que “**unsupported attribute**” ou “**unknown block**”. Après exploration via la console Terraform, il semble que certains attributs ne sont pas disponibles ou correctement référencés. En particulier, le champ model, qui est une chaîne de caractères, ne semble pas contenir les informations nécessaires pour accéder aux APs.
• Tentatives : J’ai tenté d’utiliser différents attributs (ap, devices, etc.) et d’explorer les objets disponibles via terraform console, mais sans succès.
J’aimerais savoir s’il existe une meilleure façon de récupérer et manipuler les informations des APs via le provider Mist ou si un correctif ou une mise à jour est nécessaire.
Merci d’avance pour votre aide.
Cordialement,

Contact: khadim.dieng@totalenergies.com

**Comment by tmunzer** [comment]
Bonjour @Khadimbkd , je vous contacte par email.
