### ISSUE TITLE
Hitting error when attempting to create `org:Inventory` resource 

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#5]
When attempting to create an `Inventory` resource, I hit an error `provider/org_inventory_resource.go:293 provider: devices redactedDevice, redactedDevice to redactedGuid`. It appears the root is coming from [provider/org_inventory_resource.go:293](https://github.com/Juniper/terraform-provider-mist/blob/e2c613e8b482686295bbf28d03337e4f11ce4289/internal/provider/org_inventory_resource.go#L293) as called out in the error. 

I am not sure I would anticipate this step to error out.

Please advise if this is expected.

Thanks!

**Comment by tmunzer** [comment]
Hi @zbuchheit , 

this issue should be fixed in [v0.1.18](https://github.com/Juniper/terraform-provider-mist/releases/tag/v0.1.18).
Can you check?

Thanks,

**Comment by zbuchheit** [comment]
confirmed the issue is resolved.

Thanks @tmunzer !
