### ISSUE TITLE
Issue with the mist_site_setting resource provider

### ISSUE THREAD

**Issue by Lava2014** [Juniper/terraform-provider-mist#50]
I am trying to import the site settings using the following command
# Site Setting can be imported by specifying the site_id
terraform import mist_site_setting.site_setting_one 17b46405-3a6d-4715-8bb4-6bb6d06f316a..however i am encountering the following issue

 Error: State Write Error
│
│ An unexpected error was encountered trying to retrieve type information at a given path. This is always an error in
│ the provider. Please report the following to the provider developer:
│
│ Error: AttributeName("id") still remains in the path: could not find attribute or block "id" in schema

**Comment by tmunzer** [comment]
Hi @Lava2014 , this should have been fixed in the new versions.
FYI, I made a change in the `mist_org_inventory.devices` structure. Please see [the provider documentation](https://registry.terraform.io/providers/Juniper/mist/latest/docs/resources/org_inventory) for more details.

**Comment by tmunzer** [comment]
closed for inactivity
