### ISSUE TITLE
Mist Provider unable to handle Radius Config coming back from API with `coa_port` as `""`

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#51]
I have been hitting an error `unexpected error: json: cannot unmarshal string into Go struct field siteSetting.radius_config of type int` after some changes to the UI. When looking at what the API returns, it returns the following for `radius_config`
```json
{
		"acct_servers": [],
		"auth_servers": [],
		"auth_servers_timeout": 5,
		"auth_servers_retries": 3,
		"fast_dotix_timers": false,
		"acct_interim_interval": 0,
		"auth_server_selection": "ordered",
		"coa_enabled": false,
		"coa_port": ""
	}
```

I cloned the provider and tested this, it seems like this is invalid because coa_port here is empty string and not null.

This is the test I wrote for it
```go
package resource_org_networktemplate

import (
	"encoding/json"
	"log"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/tmunzer/mistapi-go/mistapi/models"
)

func TestRadiusConfigSdkToTerraform(t *testing.T) {

	mockJSON := `{
		"acct_servers": [],
		"auth_servers": [],
		"auth_servers_timeout": 5,
		"auth_servers_retries": 3,
		"fast_dotix_timers": false,
		"acct_interim_interval": 0,
		"auth_server_selection": "ordered",
		"coa_enabled": false,
		"coa_port": ""
	}`

	var radiusConfig models.RadiusConfig
	err := json.Unmarshal([]byte(mockJSON), &radiusConfig)

	assert.NoError(t, err)
	log.Println(err)
}

```

**Comment by tmunzer** [comment]
The `coa_port` is currently not supported by Mist at the switch level (not included in the generated configuration deployed on the switches) and the UI is setting it with an empty String.

I'm removing the `coa_port` attribute from the SDK and the provider, which should fix the issue.

**Comment by tmunzer** [comment]
Hi @zbuchheit , can you test version v0.2.5?

**Comment by zbuchheit** [comment]
when running downstream tests I hit the following error

```   <ref *1> Error: invocation of junipermist:org/getInventory:getInventory returned an error: Extra OrgInventoryValue Attribute Value: While creating a OrgInventoryValue value, an extra attribute value was detected. A OrgInventoryValue must not contain values beyond the expected attribute types. This is always an issue with the provider and should be reported to the provider developers.```

**Comment by tmunzer** [comment]
Hi @zbuchheit , 

this has been fixed in v0.2.6.

thanks

**Comment by zbuchheit** [comment]
I'll take a look. Thank you! 😄

**Comment by zbuchheit** [comment]
appears fixed in latest release, thank you!
