### ISSUE TITLE
Performing refresh with `mist_device_gateway` not picking up `dhcpd_config.enabled` field changes

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#52]
When attempting the following tf code (notice the commented out enabled field), the `enabled` field will actually be set to false in the UI and state

```tf
resource "mist_device_gateway" "gateway_one" {
  name      = "gateway_one"
  device_id = "redacted"
  site_id   = "redacted"
  oob_ip_config = {
    type = "dhcp"
  }
  additional_config_cmds = ["#", "###"]
  dns_servers            = ["8.8.8.8"]
  managed                = false
  dhcpd_config = {
    # enabled = true     
    config = {
      "test" = {
        dns_servers = ["8.8.8.8", "1.1.1.1"]
        gateway = "{{test_ip}}.1"
        ip_end = "192.0.2.255"
        ip_start = "192.0.2.2"
        type = "local"
      }
    }
  }
}
```

If I change the setting to be enabled like below, a refresh won't pick up the change in state and add it to state
![image](https://github.com/user-attachments/assets/008fafdf-b054-41c3-a01b-4bf95fcf2908)

**Comment by tmunzer** [comment]
Hi @zbuchheit , can you test version v0.2.5?

**Comment by zbuchheit** [comment]
appears to be fixed in latest release.
