### ISSUE TITLE
Wi-Fi Assurance/mist_org_wlan/rateset attribute not found

### ISSUE THREAD

**Issue by nunopp** [Juniper/terraform-provider-mist#55]
I'm trying to use the "rateset" attribute of the Wi-Fi Assurance resource mist_org_wlan to configure the Geofence and Data rates configurations but I get "Unexpected attribute", any idea how can this be done? Thank you

**Comment by tmunzer** [comment]
Hi @nunopp , this property is not supported yet by the provider. 
I'll add it into the next release (should be available end of November or sooner)

**Comment by tmunzer** [comment]
Hi @nunopp ,

this has been added in v0.2.7. Can you test and validate?

Thanks

**Comment by nunopp** [comment]
I've just tested and I'm having some Errors, currently investigating if I have something wrong, I've noticed we have now v0.2.9 should I use that instead?

**Comment by tmunzer** [comment]
Thanks @nunopp .
Let me know if I can help you to fix the errors you are getting.
There is only small fixes and documentation updates between v0.2.7 and v0.2.9, it should not change much.

**Comment by nunopp** [comment]
Hi, I'm having this error now:
"Error: Missing AuthServersValue Attribute Value
While creating a AuthServersValue value, a missing attribute value was detected. A AuthServersValue must contain values for all attributes, even if null or unknown. This is always an issue with the provider and should be reported to the provider developers. AuthServersValue Attribute Name (require_message_authenticator) Expected Type: basetypes.BoolType"
which wasn't triggered before on version 0.2.6. I've added this attribute "require_message_authenticator" to the code with values (null,true or false) and none of that have fixed, any thoughts?

**Comment by tmunzer** [comment]
Thanks @nunopp ,

Can you try v0.2.10, the "require_message_authenticator" attribute has been added in the OpenAPI Spec and I didn't spotted it has been added to the Terraform Resource definitions... I fixed that in v0.2.10.

Thanks

**Comment by nunopp** [comment]
Thanks @tmunzer , the "require_message_authenticator" attribute is working now with v0.2.10.
Regarding the "ratesetup" attribute seems not working yet, doesn't give error but it's not recognizing and/or applying the configuration we do on it. Any thoughts?

**Comment by tmunzer** [comment]
Thanks @nunopp .
Regarding the `rateset`, it's working as expected on my side.
Can you share the HCL configuration of the wlan resource?

**Comment by nunopp** [comment]
Thanks, yes, think I got those names from the API before you created here, now is giving me this error:
"Attribute rateset.band_24.template value must be one of: ["" "compatible" "legacy-only" "custom" "no-legacy"], got: "high-density"
"high-density" seems not being accepted

**Comment by nunopp** [comment]
Thank you

**Comment by tmunzer** [comment]
I just published a new version v0.2.11 with the changes. Can you give it a try?

**Comment by nunopp** [comment]
It's working! Thanks for your support

**Comment by tmunzer** [comment]
Thanks for the confirmation. I'm closing the issue.
