### ISSUE TITLE
Device not found error when attempting to update to latest provider

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#56]
When attempting to update to the latest version of the provider I get the following error `Device not found: Unable to find device with Claim Code "redacted" in the Org Inventory. 

When digging through the code it looks like this error is coming from [this code snippet](https://github.com/Juniper/terraform-provider-mist/blob/57912f85904131452103ba54cb7b04f0b47e2c1e/internal/resource_org_inventory/sdk_to_terraform_legacy.go#L144-L145)

On the previous version (v0.1.44) this wasn't an issue so I am unclear on why this error is appearing now.

**Comment by zbuchheit** [comment]
As a further note, we suspect this might be a result of how creating a gateway cluster edits the resource or handles the resource in the inventory. I haven't been able to confirm but seems like a likely lead to this scenario.

**Comment by zbuchheit** [comment]
I think this situation we should be a bit cautious. If we have the scenario where the api responds back that the device isn't present any longer, it would get dropped from state, then on a subsequent run, TF would attempt to add it back into the inventory.

Do you know if this expectation is reasonable or if adding a device to a cluster does make it disappear under the inventory behind the primary node?

**Comment by tmunzer** [comment]
> As a further note, we suspect this might be a result of how creating a gateway cluster edits the resource or handles the resource in the inventory. I haven't been able to confirm but seems like a likely lead to this scenario.

There should not be any impact. The provider is using the query parameter `vc=true` to refresh the inventory. This is returning all the devices, even these parts of a cluster (gateway) or virtual chassis (switch).



> I think this situation we should be a bit cautious. If we have the scenario where the api responds back that the device isn't present any longer, it would get dropped from state, then on a subsequent run, TF would attempt to add it back into the inventory.
> 
> Do you know if this expectation is reasonable or if adding a device to a cluster does make it disappear under the inventory behind the primary node?

when a device is added to a cluster, it will still be in the Mist inventory (only visible with the query parameter `vc=true`).
For devices added with the Claim Codes, if the device is not in the Mist inventory, the provider will try to claim it again.
For devices added with the MAC Address, if the device is not in the Mist inventory the provider will NOT be able to add it back, and the provider will not be able to generate the configuration related to this specific device.

**Comment by zbuchheit** [comment]
@tmunzer thanks for your reply! It sounds like maybe this incident was caused by some other way. I wrote some test cases for legacySdkToTerraform and was able to verify the conditions that would be expected for the error to have appeared and given what you have said it makes sense to me this is unlikely to happen under normal conditions.

**Comment by tmunzer** [comment]
Hi @zbuchheit,

this should have been fixed in v0.2.7. Can you test and validate?

Thanks

**Comment by zbuchheit** [comment]
this seems to be fixed
