### ISSUE TITLE
Hitting error when attempting to update `device:base` resource

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#6]
While attempting to update my device base resource, I hit an unexpected error `resource_site/terraform_to_sdk.go:80: provider: invalid UUID length: 0` during the update operation. 

Following the referenced code, it appears the cause is [resource_site/terraform_to_sdk.go:80](https://github.com/Juniper/terraform-provider-mist/blob/e2c613e8b482686295bbf28d03337e4f11ce4289/internal/resource_site/terraform_to_sdk.go) which appears to be triggered by an invalid sitetemplate_id

Please advise if this is expected behavior

**Comment by tmunzer** [comment]
Hi @zbuchheit ,

I will remove the [error message](https://github.com/Juniper/terraform-provider-mist/blob/e2c613e8b482686295bbf28d03337e4f11ce4289/internal/resource_site/terraform_to_sdk.go#L80) in the next version.

**Comment by tmunzer** [comment]
Hi @zbuchheit , 

this issue should be fixed in [v0.1.18](https://github.com/Juniper/terraform-provider-mist/releases/tag/v0.1.18).
Can you check?

Thanks,

**Comment by zbuchheit** [comment]
confirmed the issue is resolved.

Thanks @tmunzer !
