### ISSUE TITLE
Error happened when apply routing_policies in resource "mist_org_deviceprofile_gateway"

### ISSUE THREAD

**Issue by lzhang-AIDE** [Juniper/terraform-provider-mist#60]
Set routing_policies as:
routing_policies = {
    aj-dc-in = {
        terms = [
                {
    actions = {
    accept = true
        community = [
                "65534:200"
        ]
    }
                }
        ]
    }
   }

╷
│ Error: Invalid TermsValue Attribute Type
│ 
│   with mist_org_deviceprofile_gateway.devicepolicy1,
│   on main.tf line 19, in resource "mist_org_deviceprofile_gateway" "devicepolicy1":
│   19: resource "mist_org_deviceprofile_gateway" "devicepolicy1" {
│ 
│ While creating a TermsValue value, an invalid attribute value was detected. A TermsValue must use a matching attribute type for the value. This is always an issue with the provider and
│ should be reported to the provider developers.
│ 
│ TermsValue Attribute Name (matching) Expected Type: types.ObjectType["as_path":types.ListType[basetypes.StringType], "community":types.ListType[basetypes.StringType],
│ "network":types.ListType[basetypes.StringType], "prefix":types.ListType[basetypes.StringType], "protocol":types.ListType[basetypes.StringType],
│ "route_exists":types.ObjectType["route":basetypes.StringType, "vrf_name":basetypes.StringType], "vpn_neighbor_mac":types.ListType[basetypes.StringType],
│ "vpn_path":types.ListType[basetypes.StringType], "vpn_path_sla":types.ObjectType["max_jitter":basetypes.Int64Type, "max_latency":basetypes.Int64Type, "max_loss":basetypes.Int64Type]]
│ TermsValue Attribute Name (matching) Given Type: types.ObjectType[]

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE,

this should have been fixed in v0.2.7. Can you test and validate?

Thanks

**Comment by tmunzer** [comment]
Thanks for the confirmation @lzhang-AIDE . I'm closing the issue
