### ISSUE TITLE
The provider fails when mist_org_networktemplate resource contains switch_matching.rules attribute

### ISSUE THREAD

**Issue by tnonas** [Juniper/terraform-provider-mist#61]
Inclusion of switch_matching.rules results in the following error. Please note that it occurs when:

- additional_config_cmds are not included in the attribute
- additional_config_cmds are included in the attribute (an empty list of string ["] was tested)
- additional_config_cmds attribute is or is not present in mist_org_networktemplate top level

```
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/juniper/mist" planned an invalid value for module.srx_hub_and_spoke.mist_org_networktemplate.this["branch_switch"].switch_matching.rules[0].additional_config_cmds: planned value cty.ListValEmpty(cty.String) for a
│ non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Comment by tnonas** [comment]
One correction after additional testing. The error is not present when rules section contains:

`additional_config_cmds = [""]`

**Comment by tmunzer** [comment]
this should have been fixed in v0.2.7. Can you test and validate?

**Comment by tnonas** [comment]
Tested with the current latest v0.2.9 and can confirm that it is fixed.

**Comment by tmunzer** [comment]
Thanks. I’m closing the issue.
