### ISSUE TITLE
dhcp could not be applied when it is set in mist_org_gatewaytemplate

### ISSUE THREAD

**Issue by lzhang-AIDE** [Juniper/terraform-provider-mist#64]
## Describe the bug
DHCP could not be configured in WAN Edge Template.

![Screenshot 2024-12-10 at 11 05 45 AM](https://github.com/user-attachments/assets/29b13309-98fb-44a8-9893-63d252c5a6b3)

## To Reproduce
Set dhcpd_config in "mist_org_gatewaytemplate" resource like following:
resource "mist_org_gatewaytemplate" "gatewaytemplate_CTP_MANUAL_JSEC1" {
    org_id = mist_org.terraform_test.id
    type = "spoke"
    dhcpd_config = {
    enabled = true
    CTP_CORP-WIRED_VL101 = {
    type = "local"
    ip_start = "{{ctp_corp_wired_dhcp_start}}"
    ip_end = "{{ctp_corp_wired_dhcp_end}}"
    gateway = "{{ctp_corp_wired_gw}}"
        dns_servers = [
                "{{dns1}}",
                "{{dns2}}"
        ]
        dns_suffix = [
                "{{dns_suffix}}"
        ]
    }
    lease_time= 86400
    }
    name = "CTP_MANUAL_JSEC1"
    ntp_override = true
    dns_override  = true
}

## Expected behavior
DHCP should be configured correctly.

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE ,

the DHCP configuration is a bit different from the API Structure, please see the [mist_device_gateway](https://registry.terraform.io/providers/Juniper/mist/latest/docs/resources/device_gateway#nestedatt--dhcpd_config) resource documentation
