### ISSUE TITLE
Error happened with wan_source_nat value is true in mist_org_deviceprofile_gateway

### ISSUE THREAD

**Issue by lzhang-AIDE** [Juniper/terraform-provider-mist#65]
## Describe the bug
Error happened when apply the following data:

resource "mist_org_deviceprofile_gateway" "deviceprofile_gw_one" {
  name   = "deviceprofile_gw_one"
  org_id = mist_org.terraform_test.id
  port_config = {
    "ge-0/0/3" = {
      name       = "FTTH"
      usage      = "wan"
      aggregated = false
      redundant  = false
      critical   = false
      wan_type   = "broadband"
      ip_config = {
        type    = "static"
        ip      = "192.168.1.8"
        netmask = "/24"
        gateway = "192.168.1.1"
      },
      disable_autoneg = false
      speed           = "auto"
      duplex          = "auto"
      wan_source_nat = {
        disabled = true
      },
      vpn_paths = {
        "SSR_HUB_DC-MPLS.OrgOverlay" = {
          key         = 0
          role        = "spoke"
          bfd_profile = "broadband"
        }
      }
    },
    "ge-0/0/5" = {
      usage            = "lan"
      critical         = false
      aggregated       = true
      ae_disable_lacp  = false
      ae_lacp_force_up = true
      ae_idx           = 0
      redundant        = false
      networks = [
        "PRD-Core",
        "PRD-Mgmt",
        "PRD-Lab"
      ]
    }
  }
}

## Expected behavior
wan_source_nat should be applied when its value is true.

## Error Message
![Screenshot 2024-12-17 at 1 29 24 PM](https://github.com/user-attachments/assets/44dbf752-5c99-4536-a53b-8fd33b94978e)

## Software
 - OS: [MacOS]
 - Terraform Version [v1.9.1]
 - Provider Version [latest version]

## Additional context
If change wan_source_nate value to false; there is no error.
      wan_source_nat = {
        disabled = false
      }

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE ,

I just released v0.2.13. Can you test it?

Thanks

**Comment by lzhang-AIDE** [comment]
With the latest code, there is no error happened.

Thanks.

**Comment by tmunzer** [comment]
Thanks
