### ISSUE TITLE
Plugin crashed if mist_org_deviceprofile_gateway contains tunnel_configs

### ISSUE THREAD

**Issue by lzhang-AIDE** [Juniper/terraform-provider-mist#68]
## Describe the bug
Define tunnel configs in "mist_org_deviceprofile_gateway"; when apply get error "The terraform-provider-mist plugin crashed!"

## To Reproduce
resource "mist_org_deviceprofile_gateway" "deviceprofile_test1" {
    org_id = mist_org.terraform_test.id
    tunnel_configs = {
    "J1" = {
    auto_provision = {
    provider = "jse-ipsec"
    primary = {
        probe_ips = [
                "8.8.8.8"
        ]
        wan_names = [
                "wan0"
        ]
    }
    secondary = {
        probe_ips = [
                "8.8.8.8"
        ]
        wan_names = [
                "wan0"
        ]
    }
    }
    }
    }
    name = "SVL_HUB"
    ntp_override = true
    dns_override  = true
}

## Expected behavior
tunnel_configs should be applied correctly as what we see in UI:
![Screenshot 2024-12-19 at 5 49 20 PM](https://github.com/user-attachments/assets/105585bb-5739-427c-9ddd-88284139cda7)

## Error Message
The terraform-provider-mist plugin crashed!

## Software
OS: [MacOS]
Terraform Version [v1.9.1]
Provider Version [latest version]

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE ,

I just released v0.2.13. Can you test it?

Thanks

**Comment by lzhang-AIDE** [comment]
With the latest code, there is no crash happened. 
But the Probe IPs is not applied:
![Screenshot 2024-12-20 at 11 28 51 AM](https://github.com/user-attachments/assets/3392b0f4-c4bd-4346-bc2b-f4d421a48d87)
![Screenshot 2024-12-20 at 11 29 37 AM](https://github.com/user-attachments/assets/d74b70a0-3a55-4dac-afc3-06864140f523)

Could you check @tmunzer?
Thanks.

**Comment by tmunzer** [comment]
Thanks. 
There is no `probe_ips` in the API doc for the `auto_provision` object.
I'll check that and I'll add it

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE ,

I released a new version with a lot of changes to the `tunnel_conifgs.auto_provision` object, it should now support all the supported attributes.

Can you check?

Thanks

**Comment by lzhang-AIDE** [comment]
Tested with the latest version; auto provision could be created correctly.
![Screenshot 2024-12-30 at 3 25 33 PM](https://github.com/user-attachments/assets/8ab09c76-2d4d-43e1-89cb-0b24282515c5)

Thanks

**Comment by tmunzer** [comment]
Thanks. I'm closing the issue.
