### ISSUE TITLE
Feature request (Webhooks mgmt)

### ISSUE THREAD

**Issue by steinzi** [Juniper/terraform-provider-mist#8]
My body needs webhook managment on ORG and Site level (and alerting configuration) Since these always need to be changed by our team.
![Org Level](https://github.com/user-attachments/assets/46c5dfee-14bb-460c-8ea6-72fee91c31a8)
![Site Level](https://github.com/user-attachments/assets/f0da4c85-12b7-427c-a23f-da647c4322a2)
![Alert configuration](https://github.com/user-attachments/assets/5d61f614-2fa6-43ee-9939-16235c0b69a2)

**Comment by tmunzer** [comment]
Hi @steinzi ,

Just to let you know v0.1.20 (and later) are providing Webhook management.
