### ISSUE TITLE
Running into error when creating GatewayCluster resource

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#9]
When attempting to create a GatewayCluster with multiple Nodes I get the following error

```
error: junipermist:device/gatewayCluster:GatewayCluster resource 'clusterResource' has a problem: Duplicate List Value. This attribute contains duplicate values of: NodesValue. Examine values at 'clusterResource.nodes'.
```

This occurs when creating and inventory and then a GatewayCluster in a run.

**Comment by tmunzer** [comment]
Hi @zbuchheit ,

v0.1.23 should fix the issue.

**Comment by zbuchheit** [comment]
this appears to have been fixed in the latest release
